[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "test"
version = "0.1.0"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
petgraph = {version="0.5", features = ["serde-1"]}

